### ISSUE TITLE
Syntax error after importing lib

### ISSUE THREAD

**Issue by Lqs66** [UPPAALModelChecker/uppaal-libs#14]
I downloaded the compiled `libtable.so` and `table.xml` into the same folder.
![image](https://github.com/UPPAALModelChecker/uppaal-libs/assets/62269820/c1e464e5-4455-4495-af8a-7b906d03872b)

Then I opened table.xml using uppaal and it prompted me with a syntax error.
![image](https://github.com/UPPAALModelChecker/uppaal-libs/assets/62269820/4b0e3879-6f24-48ec-b8b8-df5e26b99139)

UPPAAL version: 4.1.26-1

**Comment by mikucionisaau** [comment]
Could you please try it in Uppaal-5 ?
Uppaal 4.1.26 does not have this feature.
See also: https://docs.uppaal.org/language-reference/system-description/declarations/external-functions/
![image](https://github.com/UPPAALModelChecker/uppaal-libs/assets/4868894/bfccf4fc-4824-4d89-ab00-246a42d8f7f4)

**Comment by Lqs66** [comment]
> Could you please try it in Uppaal-5 ? Uppaal 4.1.26 does not have this feature. See also: https://docs.uppaal.org/language-reference/system-description/declarations/external-functions/ ![image](https://private-user-images.githubusercontent.com/4868894/321564734-bfccf4fc-4824-4d89-ab00-246a42d8f7f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTgzMTMsIm5iZiI6MTcxMjg5ODAxMywicGF0aCI6Ii80ODY4ODk0LzMyMTU2NDczNC1iZmNjZjRmYy00ODI0LTRkODktYWIwMC0yNDZhNDJkOGY3ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDUwMDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY4ZGIxMDZiYmJkMDFhZjliMDM0MzM4YTRjNjNmMmI1MTI1Zjc0MWNiZWVmNDM3Mjc5NmQ2NDJkNWI0ZjU4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NYhCNf1z0hVFx59NakxphOHv5vzO34r-Q8sJvQE4UWE)

Thanks for the reply.
Uppaal-5 doesn't make such syntax errors.
